services:

  backend:
    build: ./backend

    container_name: network-automation-backend

    env_file:
      - .env

    ports:
      - "8000:8000"

    restart: unless-stopped


  frontend:
    build: ./frontend

    container_name: network-automation-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped
